### ISSUE TITLE
Current method of storing password is unsafe

### ISSUE THREAD

**Issue by mssalkhalifah** [Kaalotaibi37/dino-run#2]
The current method of storing password is insecure. Look into `password_hash` and `password_verify`. MD5 encryption is not safe for storing password because it can be easily brute forced. And it does not salt the password. 

https://github.com/Kaalotaibi37/chrome-dinosaur-game/blob/3900c82374d6d445280f6254a072ba6d5e2e4523/server.php#L35
https://github.com/Kaalotaibi37/chrome-dinosaur-game/blob/3900c82374d6d445280f6254a072ba6d5e2e4523/server.php#L60

**Comment by Maas-99** [comment]
all done. password is now hashed and salted.
